// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJN8A1Nbm_N3OsnAGRMBcebwSqCya1IHo',
    appId: '1:207825433961:web:0c686d3443adfb1ab739f8',
    messagingSenderId: '207825433961',
    projectId: 'uz-shopmanager',
    authDomain: 'uz-shopmanager.firebaseapp.com',
    databaseURL: 'https://uz-shopmanager-default-rtdb.firebaseio.com',
    storageBucket: 'uz-shopmanager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1fA_3HFTjg4q4eqQVce5G5rsSegM6Vg',
    appId: '1:207825433961:android:d0dc0493547c5340b739f8',
    messagingSenderId: '207825433961',
    projectId: 'uz-shopmanager',
    databaseURL: 'https://uz-shopmanager-default-rtdb.firebaseio.com',
    storageBucket: 'uz-shopmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNcC7tYO39quESSBCbYruAqywCWukA8jk',
    appId: '1:207825433961:ios:07f257e9435b323bb739f8',
    messagingSenderId: '207825433961',
    projectId: 'uz-shopmanager',
    databaseURL: 'https://uz-shopmanager-default-rtdb.firebaseio.com',
    storageBucket: 'uz-shopmanager.appspot.com',
    androidClientId: '207825433961-ban9olhdcpq6etagq9arkb2jl7gvhurb.apps.googleusercontent.com',
    iosClientId: '207825433961-o4mcvs1kb3pug9gm32v31vbuvuhd23rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopmanagerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNcC7tYO39quESSBCbYruAqywCWukA8jk',
    appId: '1:207825433961:ios:07f257e9435b323bb739f8',
    messagingSenderId: '207825433961',
    projectId: 'uz-shopmanager',
    databaseURL: 'https://uz-shopmanager-default-rtdb.firebaseio.com',
    storageBucket: 'uz-shopmanager.appspot.com',
    androidClientId: '207825433961-ban9olhdcpq6etagq9arkb2jl7gvhurb.apps.googleusercontent.com',
    iosClientId: '207825433961-o4mcvs1kb3pug9gm32v31vbuvuhd23rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopmanagerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFf9PaA9jzbF3D_OqiA8b24D5YhYIrBd4',
    appId: '1:207825433961:web:98896bfcb10432ffb739f8',
    messagingSenderId: '207825433961',
    projectId: 'uz-shopmanager',
    authDomain: 'uz-shopmanager.firebaseapp.com',
    databaseURL: 'https://uz-shopmanager-default-rtdb.firebaseio.com',
    storageBucket: 'uz-shopmanager.appspot.com',
  );
}
